/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.champeau.mrjar;

import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.artifacts.ConfigurationContainer;
import org.gradle.api.artifacts.dsl.DependencyHandler;
import org.gradle.api.model.ObjectFactory;
import org.gradle.api.plugins.ExtensionContainer;
import org.gradle.api.plugins.JavaPlugin;
import org.gradle.api.plugins.JavaPluginExtension;
import org.gradle.api.plugins.PluginManager;
import org.gradle.api.tasks.TaskContainer;
import org.gradle.jvm.toolchain.JavaToolchainService;

import javax.inject.Inject;

/**
 * A plugin which adds support for building multi-release jars
 * with Gradle.
 */
public class MultiReleaseJarPlugin implements Plugin<Project> {

    @Inject
    protected JavaToolchainService getToolchains() {
        throw new UnsupportedOperationException();
    }

    public void apply(Project project) {
        project.getPlugins().apply(JavaPlugin.class);
        ExtensionContainer extensions = project.getExtensions();
        JavaPluginExtension javaPluginExtension = extensions.getByType(JavaPluginExtension.class);
        PluginManager pluginManager = project.getPluginManager();
        ConfigurationContainer configurations = project.getConfigurations();
        TaskContainer tasks = project.getTasks();
        DependencyHandler dependencies = project.getDependencies();
        ObjectFactory objects = project.getObjects();
        extensions.create("multiRelease", MultiReleaseExtension.class,
                javaPluginExtension,
                javaPluginExtension.getSourceSets(),
                configurations,
                getToolchains(),
                tasks,
                dependencies,
                objects,
                pluginManager,
                extensions);
    }
}
